on:
  release:
    types: [published]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          default: true
          override: true

      - name: Build for Mac
        run: cargo build --all --release && strip target/release/kapacitet && mv target/release/kapacitet target/release/kapacitet

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/kapacitet
          asset_name: kapacitet-${{ github.ref_name }}
          tag: ${{ github.ref }}
          overwrite: true
